### ISSUE TITLE
KiCad Files

### ISSUE THREAD

**Issue by antimatter15** [hxelec/s3p#1]
It looks like the Kicad schematic files are mentioned in the README but they aren't in the repo, were they not uploaded by accident?

**Comment by hxelec** [comment]
Oh, yeah. I just uploaded them, sorry about that.

**Comment by antimatter15** [comment]
Thanks! Also in a few years you should consider applying to MIT, we would be lucky to have you!

**Comment by hxelec** [comment]
Thanks! Yeah, I probably will, that would be really awesome.
