### ISSUE TITLE
License

### ISSUE THREAD

**Issue by SoupySoups** [hxelec/s3p#2]
There is no license in this repository. With the fact that this is a WIP, what terms would you like this schematic to be used under? 

For my use case am I specifically asking about use with modification and attribution for non-commercial use.

**Comment by hxelec** [comment]
Hi Camden,

Sure, you can do that. Sorry for the late reply, I’d be happy for you to
make a board for non-commercial use with attribution. Please let me know
when you are done making it, would love to see it! I’ll add a license into
this GitHub now, thanks.

**Comment by SoupySoups** [comment]
Thanks so much :)
